<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_585abac9ba67d',
	'title' => 'Landing',
	'fields' => array (
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_585d00e3e5a46',
			'label' => 'Sections',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'layouts' => array (
				array (
					'key' => '585d013e14b39',
					'name' => 'landing_sections_quote',
					'label' => 'Quote',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'default_value' => '',
							'new_lines' => 'br',
							'maxlength' => '',
							'placeholder' => '',
							'rows' => 4,
							'key' => 'field_585d0158a94cd',
							'label' => 'Title',
							'name' => 'landing_sections_quote_title',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'key' => 'field_586b97031d1be',
							'label' => 'Text Color',
							'name' => 'landing_sections_quote_text_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => 0,
							'message' => 'Bold',
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'key' => 'field_586d20c941fb9',
							'label' => 'Text Weight',
							'name' => 'landing_sections_quote_text_weight',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'key' => 'field_585d01dda94cf',
							'label' => 'Author',
							'name' => 'landing_sections_quote_author',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'return_format' => 'url',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => 'png,svg',
							'key' => 'field_585d10e21a299',
							'label' => 'Author Image',
							'name' => 'landing_sections_quote_author_image',
							'type' => 'file',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '#FFFFFF',
							'key' => 'field_585d117929f2c',
							'label' => 'Background Color',
							'name' => 'landing_sections_quote_background_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg,jpeg,png,gif,svg',
							'key' => 'field_585d0190a94ce',
							'label' => 'Background Image',
							'name' => 'landing_sections_quote_background_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '586cfa3706fc8',
					'name' => 'landing_sections_features',
					'label' => 'Features',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'default_value' => '',
							'new_lines' => 'br',
							'maxlength' => '',
							'placeholder' => '',
							'rows' => 2,
							'key' => 'field_586cfa6c06fc9',
							'label' => 'Title',
							'name' => 'landing_sections_features_title',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'new_lines' => 'wpautop',
							'maxlength' => '',
							'placeholder' => '',
							'rows' => 2,
							'key' => 'field_586cfa8e06fca',
							'label' => 'Text',
							'name' => 'landing_sections_features_text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'sub_fields' => array (
								array (
									'return_format' => 'url',
									'library' => 'all',
									'min_size' => '',
									'max_size' => '',
									'mime_types' => 'svg,png',
									'key' => 'field_586cfae506fcc',
									'label' => 'Icon',
									'name' => 'landing_sections_features_group_icon',
									'type' => 'file',
									'instructions' => 'Square icons optimized for 64x64px',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
								),
								array (
									'default_value' => '',
									'new_lines' => 'wpautop',
									'maxlength' => '',
									'placeholder' => '',
									'rows' => 4,
									'key' => 'field_586cfb1b06fcd',
									'label' => 'Text',
									'name' => 'landing_sections_features_group_text',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
								),
							),
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Add Feature',
							'collapsed' => 'field_586cfb1b06fcd',
							'key' => 'field_586cfac606fcb',
							'label' => 'Features',
							'name' => 'landing_sections_features_group',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => 480,
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'png',
							'key' => 'field_586cfb5f06fce',
							'label' => 'Image',
							'name' => 'landing_sections_features_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '585d04821ce7f',
					'name' => 'landing_sections_form',
					'label' => 'Form',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'placement' => 'top',
							'endpoint' => 0,
							'key' => 'field_585d05c1a7db7',
							'label' => 'Quote',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'new_lines' => 'br',
							'maxlength' => '',
							'placeholder' => '',
							'rows' => 4,
							'key' => 'field_586cf53866532',
							'label' => 'Title',
							'name' => 'landing_sections_form_quote_title',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'key' => 'field_586cf59166533',
							'label' => 'Author',
							'name' => 'landing_sections_form_quote_author',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'placement' => 'top',
							'endpoint' => 0,
							'key' => 'field_585d05b3a7db6',
							'label' => 'Form',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'default_value' => '',
							'new_lines' => 'br',
							'maxlength' => '',
							'placeholder' => '',
							'rows' => 2,
							'key' => 'field_585d04981ce80',
							'label' => 'Title',
							'name' => 'landing_sections_form_title',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array (
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 0,
							'default_value' => '',
							'delay' => 0,
							'key' => 'field_585d04c21ce81',
							'label' => 'Body',
							'name' => 'landing_sections_form_body',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Add Section',
			'key' => 'field_585d012fa94cc',
			'label' => 'Sections',
			'name' => 'landing_sections',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_585d00b1e5a44',
			'label' => 'Hero',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'message' => 'Hero will be displayed only on the front page.',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
			'key' => 'field_585d531b7b51a',
			'label' => 'Hero',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => 4,
			'key' => 'field_585d004ae5a43',
			'label' => 'Title',
			'name' => 'landing_hero_title',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'svg,png',
			'key' => 'field_586d0aefd7b04',
			'label' => 'Wordmark',
			'name' => 'landing_hero_wordmark',
			'type' => 'file',
			'instructions' => 'Image will be limited to 90px width',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_585d00c5e5a45',
			'label' => 'Arrow',
			'name' => 'landing_hero_arrow',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-pages/landing.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'featured_image',
		5 => 'categories',
		6 => 'tags',
		7 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_585d076b11140',
	'title' => 'Theme Options',
	'fields' => array (
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_585d098ee9c42',
			'label' => 'Social',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 1200,
			'min_height' => 640,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => 1,
			'mime_types' => 'jpg,jpeg',
			'key' => 'field_585d099ae9c43',
			'label' => 'Image',
			'name' => 'options_social_image',
			'type' => 'image',
			'instructions' => 'According to the guidelines of Facebook and Twitter the image must be at least 1200x640 with maximum file size of 1MB.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_585d0aaf67787',
			'label' => 'Statistics',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '0oo00-Uo000-0o0o0o0o0o0o',
			'prepend' => '',
			'append' => '',
			'key' => 'field_585d0b63ac01f',
			'label' => 'Google Site Verification',
			'name' => 'options_google_site_verification',
			'type' => 'text',
			'instructions' => 'Enter the number generated by Google Site Verification',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '(function(){i[\'…\']=x;y[0];',
			'prepend' => '',
			'append' => '',
			'key' => 'field_585d0abe67788',
			'label' => 'Code',
			'name' => 'options_statistics_code',
			'type' => 'text',
			'instructions' => 'Insert the JavaScript code generated by the statistics service',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_585d08a51bf43',
			'label' => 'Form',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_585d08b61bf44',
			'label' => 'Button',
			'name' => 'options_form_button',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_585d093876033',
			'label' => 'MailChimp ID',
			'name' => 'options_form_mailchimp',
			'type' => 'text',
			'instructions' => 'Full url of MailChimp List ID',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'placement' => 'top',
			'endpoint' => 0,
			'key' => 'field_585d077975c29',
			'label' => 'Footer',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'svg',
			'key' => 'field_585d07c775c2b',
			'label' => 'Icon',
			'name' => 'options_footer_icon',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'default_value' => '',
			'delay' => 0,
			'key' => 'field_585d079275c2a',
			'label' => 'Text Column 1',
			'name' => 'options_footer_column_1',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'default_value' => '',
			'delay' => 0,
			'key' => 'field_586cf11e32be1',
			'label' => 'Text Column 2',
			'name' => 'options_footer_column_2',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
		),
		array (
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'key' => 'field_585d07ec75c2c',
			'label' => 'Copyright',
			'name' => 'options_footer_copyright',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
